name: default
channels:
- conda-forge
- nodefaults
dependencies:
- python 3.12.*
- ase >=3.26.0,<4
- ipywidgets >=8.1.7,<9
- jupyterlab >=4.4.6,<5
- matplotlib >=3.10.5,<4
- nglview >=3.1.4,<4
- rdkit >=2025.3,<2026
- tblite-python >=0.4.0,<0.5
- mopac >=23.1.2,<24
- jupyterlab-myst >=2.4.2,<3
- pip
- pip:
  - -e .
  - pymopac>=1.1, <2
  - sella>=2.3.5, <3
