name: achprak
channels:
  - conda-forge
  - https://mvondomaros-lab.github.io/conda
dependencies:
  - python=3.12
  - jupyterlab
  - jupyterlab-myst
  - ipywidgets
  - nglview
  - matplotlib
  - mvdlib
  - ase
  - mopac
  - rdkit
  - tblite-python
  - pip:
    - pymopac
    - sella
